version: "3"
networks: #all of these containers will share a network
  loki:

services: 
  vector: # loki does not support ARM-based CPU:s and therefore the vector service had to be added
    image: timberio/vector:0.18.1-debian
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /Users/lbw504/Desktop/grafana_loki/vector/vector-config.toml:/etc/vector/vector.toml:ro
    ports:
        - "8383:8383"
    restart: unless-stopped
    networks:
      - loki

  loki:
    image: grafana/loki:2.4.0
    volumes:
      - /Users/lbw504/Desktop/grafana_loki/loki:/etc/loki #path and mapping that to inside of container
    ports:
      - "3100:3100"
    restart: unless-stopped
    command: -config.file=/etc/loki/loki-config.yml #loki config
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.4.0
    volumes:
      - /var/log:/var/log # can i use this?
      - /Users/lbw504/Desktop/grafana_loki/promtail:/etc/promtail
    # ports:
    #   - "1514:1514" # this is only needed if you are going to send syslogs
    restart: unless-stopped
    command: -config.file=/etc/promtail/promtail-config.yml
    networks:
      - loki
  grafana:
    image: grafana/grafana:latest
    user: "1000" # uid 
    volumes:
    - /Users/lbw504/Desktop/grafana_loki/grafana:/var/lib/grafana
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - loki
